### ISSUE TITLE
check_password(passwd,local_passwd)

### ISSUE THREAD

**Issue by haiya512** [SingleCorner/AutoO_with_django#1]
说明文档很少啊，用户也不知道怎么去创建

**Comment by SingleCorner** [comment]
Thank for ths issue.
这个问题目前还有问题。
现在只是做数据库初始化的时候会加载admin，文档的话我会尽快更新。

**Comment by SingleCorner** [comment]
此问题将在cherie项目里面得到解决，解决方案如下：
1.提供自助注册接口，暂不做验证，填写账号密码即可直接注册

**Comment by SingleCorner** [comment]
此问题将在cherie项目里面得到解决，解决方案如下：
1.提供自助注册接口，暂不做验证，填写账号密码即可直接注册
2.首位注册用户将获得任意权限，可对任意用户修改数据。
3.id为1的用户不可删除，不可禁用登录，如果不慎被删，请在数据库中设置一个id为1的用户

详细的文档请关注本人基于此项目的python3版本cherie项目，谢谢关注此项目
